

// Outer dependencies

include(reflect_pull('dir').'../../util/MathUtils.ms');
include(reflect_pull('dir').'../../util/Menus/Menu.ms');
include(reflect_pull('dir').'../../util/LocationNormalization.ms');
include(reflect_pull('dir').'../../util/RegionUtils.ms');
include(reflect_pull('dir').'../../util/Chat/ChatUtils.ms');
include(reflect_pull('dir').'../../util/FightUtils/FightUtils.ms');

// Inner dependencies
include(reflect_pull('dir').'minigameLocations.ms');
