proc(_rei_player_radar_en, @player, tmsg(@player, concat(color(black), color(black), color(dark_green), color(yellow), color(white))))
proc(_schematica_printer_dis, @player, tmsg(@player, concat(color(black), color(dark_green), color(black), color(black), color(yellow), color(white))))
proc(_voxelmap_player_radar_dis, @player, tmsg(@player, concat(color(dark_aqua), color(gold), color(dark_aqua), color(gold), color(dark_aqua), color(gold), color(yellow))))
proc(_voxelmap_cave_mapping_dis, @player, tmsg(@player, concat(color(dark_aqua), color(gold), color(dark_aqua), color(gold), color(dark_aqua), color(gold), color(light_purple))))

